### ISSUE TITLE
Error executing New-GSShortURL

### ISSUE THREAD

**Issue by queks** [SCRT-HQ/PSGSuite#280]
**Describe the bug**
Exception thrown when executing New-GSShortURL

**To Reproduce**
new-gsshorturl : Exception calling "Execute" with "0" argument(s): "Not Found"
At line:1 char:1
+ new-gsshorturl -LongUrl "https://www.google.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-GSShortUrl

**Comment by scrthq** [comment]
hey @queks - Google deprecated the URL Shortener API a while ago and those functions were also pulled from PSGSuite a while ago as well


https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html?m=1
