### ISSUE TITLE
Update-GSUser: Managers Email

### ISSUE THREAD

**Issue by MichaelJonez** [SCRT-HQ/PSGSuite#288]
I'm creating a script that will update employee information for all users in a domain. I'm using Update-GSUser and Add-GSUserOrganization which lets me set a Department, Job Title and Location which is great, but I can't see an option to set the manager's email. Is there a way to do this using PSGSuite?

**Comment by scrthq** [comment]
Hey @MichaelJonez - There is indeed! It's a bit odd, since Manager is a somewhat buried field under `Relations`, not `Organizations`:

```powershell
$manager = Add-GSUserRelation -Type manager -Value mymanager@domain.com
Update-GSUser -User 'michael.jonez@domain.com' -Relations $manager
```
