### ISSUE TITLE
"Company owned" devices are not reported

### ISSUE THREAD

**Issue by lucafabbri365** [SCRT-HQ/PSGSuite#291]
Hello,
I noticed the `Get-GSMobileDevice` doesn't report the list of devices registered as _company owned_.
It is the same behavior while using Google tool **Try this API** at the link [Mobiledevices: list](https://developers.google.com/admin-sdk/directory/v1/reference/mobiledevices/list), using the filter:
- **customerId** = \<CustomerId>
- **query** = serial:\<SerialNumber> (it is the serial number of company owned device appearing on G Suite console; if I specify a serial number of any _User owned_ device, then it works).

**Note:** "_query_" field syntax is provided by [Use search operators to find devices](https://support.google.com/a/answer/7549103) > _Company-owned device search operators_ section

So the question is: how is it possible Google isn't allowing company owned devices to be searched via API ? I cannot believe that. So, what did I miss ?

Thank you,
Luca

**Comment by scrthq** [comment]
Hey @lucafabbri365 - How are you currently determining if a device is company owned or not in the Admin Console? We use MDM, but primarily for device policy enforcement on BYOD mobile devices, so I honestly haven't used the APIs or the UI for searching for company-owned devices. It seems like you're getting the same results though when using the API Explorer as you are with PSGSuite, so I'm wondering if this would be a better question for Google / the team that supports that API?

**Comment by lucafabbri365** [comment]
Hello @scrthq,
in Admin Console the "Ownership" column identifies if a device is "User owned" (BYOD) or "Company owned". Company devices are those registered under _Device management  > Company owned inventory_ section. 
As I can see it's a Google API limit and, to be honest, it doesn't make any sense to me: a mobile device, is a mobile device either _company owned_ or _user owned_; so why an API with generic name _Mobiledevices_ should return user owned only devices and not company owned ?

**Comment by lucafabbri365** [comment]
Hello @scrthq,
I'm going to close the issue because not related to PSGSuite.

Bye,
Luca
