### ISSUE TITLE
Sync-GSUserCache error

### ISSUE THREAD

**Issue by IronKane2** [SCRT-HQ/PSGSuite#298]
I've been running this script hourly for over a year with no issues.  Is there an upper limit to the GSUserCache?

Executing this:
$GSUsers = Sync-GSUserCache -PassThru -verbose

Produces this:
VERBOSE: Syncing users to $global:GSUserCache
VERBOSE: Building ServiceAccountCredential from P12Key as user 'srcampbell@djusd.net'
VERBOSE: Getting all Users for customer '########'
VERBOSE: Retrieved 500 users...
blah blah blah
VERBOSE: Retrieved 17000 users...

Get-GSUser : Exception calling "Execute" with "0" argument(s): "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 
'System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Object]]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize 
correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like 
List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'users[435].customSchemas', line 19076, position 24."
At C:\Program Files\WindowsPowerShell\Modules\PSGSuite\2.35.1\PSGSuite.psm1:29469 char:9
+         Get-GSUser -Filter $Filter | ForEach-Object {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSUser

**Comment by scrthq** [comment]
Hey @IronKane2 - There shouldn't be an upper limit; all the UserCache is is a local variable containing an array. That being said, we saw similar issues with the Admin SDK failing to deserialize the customSchemas value as well a few days ago; it appeared that Google was returning an array instead of a dictionary for the customSchemas value, resulting in the .NET SDK failing to deserialize to the expected value. I'm assuming you're also no longer seeing this error?

**Comment by IronKane2** [comment]
HI Nate,

I think it was Google that was having the issue.  Later on it started working and I haven’t seen a repeat.  I updated my script and wrapped my code with an If count > 0 so it wouldn’t proceed if my hash table was empty.  Thanks for your response.  You can close the ticket.

-Steve
