### ISSUE TITLE
Get-GSUser -Filter "Suspended -eq '$true'" causes exception

### ISSUE THREAD

**Issue by sctib** [SCRT-HQ/PSGSuite#311]
I can run these and get the expected result:
Get-GSUser -Filter "IsMailboxSetup -eq '$true'" | select-object user
Get-GSUser -Filter "IsEnrolledIn2sv -eq '$true'" | select-object user

but when I run:
Get-GSUser -Filter "Suspended -eq '$true'" | select-object user

I get the error:

Get-GSUser : Exception calling "Execute" with "0" argument(s): "Google.Apis.Requests.RequestError
Invalid Input: query [400]
Errors [
        Message[Invalid Input: query] Location[ - ] Reason[invalid] Domain[global]
]
"
At line:1 char:1
+ Get-GSUser -Filter "Suspended -eq '$true'" | select-object user
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GSUser

 - OS:  Windows Server 2019
 - PowerShell Version: Windows PowerShell 5.1.14409.1018
 - PSGSuite Version:  latest

**Comment by boxstack** [comment]
@sctib: use IsSuspended instead ->  Get-GSUser -Filter "IsSuspended -eq '$true'"

**Comment by sctib** [comment]
> @sctib: use IsSuspended instead -> Get-GSUser -Filter "IsSuspended -eq '$true'"

Thanks! It helps to read the documentation:-)
