### ISSUE TITLE
set-psgsuiteconfig not giving me a config

### ISSUE THREAD

**Issue by poseyjmac** [SCRT-HQ/PSGSuite#315]
There aren't any errors, so I'm unsure what's going on. I input all the required info, but I don't see a config file appear anywhere after I run the command. Any ideas?

**Comment by FISHMANPET** [comment]
The module uses the Configuration module, which will place it (if doing a user Config, on Windows), at `~\AppData\Local\powershell\SCRT HQ\PSGSuite\Configuration.psd1`.  A machine config will go to `%PROGRAMDATA%\powershell\SCRT HQ\PSGSuite\Configuration.psd1`.  I'm not sure off the top of my head where they'd go in Unix.

**Comment by poseyjmac** [comment]
Thanks
