### ISSUE TITLE
Get-GSGmailSignature

### ISSUE THREAD

**Issue by skywayskase** [SCRT-HQ/PSGSuite#347]
**Is your feature request related to a problem? Please describe.**
Currently I need to use GAM for getting a users existing signature. I typically use this for testing and verification purposes when doing forced signature updates for my company.

**Describe the solution you'd like**
I would like a Get-GSGmailSignature function to be added to this module. This will get me one step closer to replacing GAM in my scripts.

**Describe alternatives you've considered**
Currently I use GAM to get user signatures, but I'd like to replace GAM with PSGSuite as much as possible.

**Comment by phatmandrake** [comment]
Get-GSGMailSignature is an alias of Get-GSGmailSendAsAlias, which will return the output you're looking for.

**Comment by skywayskase** [comment]
Oh hey, look at that.. Welp, thanks for the tip!
