### ISSUE TITLE
Get-GSChromeOSDevice returning weird data

### ISSUE THREAD

**Issue by gmorrow3** [SCRT-HQ/PSGSuite#349]
**Describe the bug**
when running Get-GSChromeOSDevice much of the data is correct, there are various bits that return "Google.Apis.Admin.Directory.directory_v1.Data.ChromeOsDevice+" and whatever the field name is: Google.Apis.Admin.Directory.directory_v1.Data.ChromeOsDevice+RecentUsersData instead of the data that is in that place.

**To Reproduce**
1. Run Get-GSChromeOSDevice
2. See data

**Expected behavior**
I expect to see the proper data in these fields
Maybe I set something up incorrectly, or maybe I'm just stupid (that is highly likely)

**Screenshots**
![image](https://user-images.githubusercontent.com/50112005/115591016-41a49a80-a297-11eb-89bf-f1a06b4b0eee.png)

**Environment (please complete the following information):**
 - OS:  Windows 10 Pro Build 19042
 - PowerShell Version:  5.1.19041.610
 - PSGSuite Version:  2.24.0 and 2.36.4

**Comment by Buenno** [comment]
Hi, 

You need to use -ExpandProperty in Select-Object in order to expand the nested objects.

**Comment by gmorrow3** [comment]
> Hi,
> 
> You need to use -ExpandProperty in Select-Object in order to expand the nested objects.

Ah!  I see now, working as expected when formatted properly... Thank you very much!
